os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} "{{filename}}"'
gui:
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - '#004469'
  customIcons:
    gitStatus:
      "deleted": ''
      "renamed": '󰁕'
      "modified": '󰓎'
      "ignored": ''
      "added": ''
      "untracked": ''
      "conflict": ''
